# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LDAV 2017
email: ldav@ieeevis.org
description: > # this means to ignore newlines until "baseurl:"
  The 7th IEEE Symposium on Large Data Analysis and Visualization
  in conjunction with IEEE VIS 2017, Phoenix, Arizona, October 2, 2017
baseurl: "~garth/ldav/" # the subpath of your site, e.g. /blog
url: "http://vis.uni-kl.de" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: 

exclude:
  - Gemfile
  - Gemfile.lock
  - misc

# site setup
collections: 
  pages:
    output: true
    permalink: /:path:output_ext

navigation:
 - title: Home
   url: index.html
 - title: Call for Papers
   url: call-for-papers.html
 - title: Call for Posters
   url: call-for-posters.html
 - title: Supporters
   url: supporters.html
 - title: Important Dates
   url: important-dates.html
 - title: Organization
   url: organization.html
#  - title: Presenter Information
#    url: presenters.html
#  - title: LDAV 2016
#    url: 2016/
#  - title: LDAV 2015
#    url: 2015/
#  - title: LDAV 2014
#    url: 2014/
