
title: LDAV 2017
email: ldav@ieeevis.org
baseurl: ""
url: "http://ldav.org"

description: > 
  The 7th IEEE Symposium on Large Data Analysis and Visualization,
  in conjunction with IEEE VIS 2017, Phoenix, Arizona, October 2, 2017


# Build settings
markdown: kramdown

gems: 
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - misc

# site setup
collections: 
  pages:
    output: true
    permalink: /:path:output_ext

navigation:
 - title: Home
   url: index.html
 - title: Call for Papers
   url: call-for-papers.html
 - title: Call for Posters
   url: call-for-posters.html
#  - title: Supporters
#    url: supporters.html
 - title: Important Dates
   url: important-dates.html
 - title: Organization
   url: organization.html
#  - title: Presenter Information
#    url: presenters.html
#  - title: LDAV 2016
#    url: 2016/
#  - title: LDAV 2015
#    url: 2015/
#  - title: LDAV 2014
#    url: 2014/
